version: '3.7'
services:
  postgres:
    container_name: microservice_postgres
    image: postgres:${POSTGRES_VERSION}
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - /data/postgres/
    networks:
      - microservice-network

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    ports:
      - 15672:15672
      - ${RABBITMQ_FIRST_HOST_PORT}:5672
    networks:
      - microservice-network

  eventstore:
    container_name: microservice_eventstore
    ports:
      - ${EVENT_STORE_HTTP_PORT}:2113
      - ${EVENT_STORE_TCP_PORT}:1113
    image: eventstore/eventstore:${EVENT_STORE_VERSION}
    # thanks to this command we can connect to the eventstore
    command: --dev --enable-external-tcp --ext-ip=0.0.0.0 --int-ip=0.0.0.0 --disable-external-tcp-tls
    environment:
      - EVENTSTORE_CLUSTER_SIZE=${EVENT_STORE_CLUSTER_SIZE}
      - EVENTSTORE_INT_TCP_PORT=${EVENT_STORE_INT_TCP_PORT}
      - EVENTSTORE_EXT_TCP_PORT=${EVENT_STORE_EXT_TCP_PORT}
      - EVENTSTORE_INT_HTTP_PORT=${EVENT_STORE_INT_HTTP_PORT}
      - EVENTSTORE_EXT_HTTP_PORT=${EVENT_STORE_EXT_HTTP_PORT}
      # later we will provide a certificate for TLS connection to event store
      - EVENTSTORE_INSECURE=${EVENT_STORE_INSECURE}
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true

networks:
  microservice-network:
    driver: bridge
